sonar.organization=manisaiteja
sonar.projectKey=ManiSaiTeja2007_Portfolio
sonar.projectName=Portfolio
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.sourceEncoding=UTF-8
